-- insert into product(id, name, cat_Id) values (1, 'Apples', 1)
-- -- insert into product(id, name, cat_Id) values (2, 'Bananas', 1)
-- -- insert into product(id, name, cat_Id) values (3, 'Oranges', 1)
-- -- insert into product(id, name, cat_Id) values (4, 'Carrot', 2)